apiVersion: v1
kind: Service
metadata:
  name: service-b
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: BRKOPS-3603-demo
    service: service-b
  type: ClusterIP
