apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: cl2025-instrumentation
  annotations:
    instrumentation.opentelemetry.io/default-auto-instrumentation-apache-httpd-image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-apache-httpd:1.0.4
    instrumentation.opentelemetry.io/default-auto-instrumentation-dotnet-image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-dotnet:1.2.0
    instrumentation.opentelemetry.io/default-auto-instrumentation-go-image: ghcr.io/open-telemetry/opentelemetry-go-instrumentation/autoinstrumentation-go:v0.14.0-alpha
    #instrumentation.opentelemetry.io/default-auto-instrumentation-java-image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-java:1.33.5
    instrumentation.opentelemetry.io/default-auto-instrumentation-java-image: ghcr.io/signalfx/splunk-otel-java/splunk-otel-java:v2.7.0
    instrumentation.opentelemetry.io/default-auto-instrumentation-nginx-image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-apache-httpd:1.0.4
    instrumentation.opentelemetry.io/default-auto-instrumentation-nodejs-image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-nodejs:0.52.1
    instrumentation.opentelemetry.io/default-auto-instrumentation-python-image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-python:0.48b0
spec:
  java:
    env:
    - name: OTEL_RESOURCE_ATTRIBUTES
      value: deployment.environment=$(NAMESPACE),service.name=$(SERVICE_NAME),service.namespace=$(NAMESPACE),splunk.zc.method=splunk-otel-java:v2.7.0
    - name: OTEL_EXPORTER_OTLP_ENDPOINT
      value: http://otel-collector:4318
    #image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-java:1.29.0
    image: ghcr.io/signalfx/splunk-otel-java/splunk-otel-java:v2.7.0
    resources:
      limits:
        cpu: 500m
        memory: 64Mi
      requests:
        cpu: 50m
        memory: 64Mi
  exporter:
    endpoint: http://otel-collector:4317 
  propagators:
  - tracecontext
  - baggage
  - b3
  sampler:
    type: always_on
    argument: "1"

