[extend]
# useDefault will extend the base configuration with the default gitleaks config:
# https://github.com/gitleaks/gitleaks/blob/master/config/gitleaks.toml
useDefault = true

[[rules]]
id = "appd-access-token"
description = "Identifies patterns indicative of AppDynamics credentials, preventing unauthorized resource access and potential data breaches."
regex = '''accessKey:\s[a-z0-9-]+'''

[[rules]]
id = "appd-globalAccount"
description = "Detect globalAccount with specific pattern"
regex = '''globalAccount:\s[a-z0-9\-_]+_([a-z0-9\-]+)'''
# The regular expression breakdown:
# - `globalAccount:\s`: matches "globalAccount:" followed by a space
# - `[a-z0-9]+`: matches one or more lowercase letters or digits
# - `(-[a-z0-9]+){4}`: matches exactly four groups of a hyphen followed by one or more lowercase letters or digits

