apiVersion: v1
kind: Service
metadata:
  name: web-frontend
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: DemoApp
    service: web-frontend
  type: ClusterIP
