apiVersion: v1
data:
  config.json: "{\"appName\": \"DemoApp\", \"imageNamePrefix\": \"astoklas177/\",\
    \ \"imageVersion\": \"v0.0.2\", \"type\": \"java\", \"endpoints\": {\"http\":\
    \ {\"/account/login\": [\"sql://sessiondb/policy?query=INSERT INTO sessions(user,data)\
    \ VALUES('user1',123)\", \"sql://sessiondb/policy?query=INSERT INTO sessions(user,data)\
    \ VALUES('user2',987)\"], \"/account/home\": [\"slow,524\", {\"call\": \"error,500,Oops\"\
    , \"probability\": 0.3}], \"/account/logout\": [\"sql://sessiondb/session?query=INSERT\
    \ INTO audit(user,audittrail) VALUES('user1',1)\", \"sql://sessiondb/session?query=INSERT\
    \ INTO audit(user,audittrail) VALUES('user2',0)\"], \"/healthz\": [\"slow,128\"\
    ]}}, \"agent\": false, \"serviceName\": \"account\"}  \n"
kind: ConfigMap
metadata:
  name: account-json
